# Coolify Configuration
# Este archivo le dice a Coolify c贸mo deployar la aplicaci贸n

version: "1.0"

# Configuraci贸n del build
build:
  dockerfile: Dockerfile
  context: .
  
# NO hacer push al registry
registry:
  enabled: false
  
# Configuraci贸n del contenedor
container:
  port: 3000
  
# Variables de entorno (se sobrescriben con las de Coolify UI)
environment:
  NODE_ENV: production
  PORT: 3000
  HOSTNAME: "0.0.0.0"

