[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]
nixLibs = ["gcc-unwrapped"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

