[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = ["curl", "wget"]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit"
]

[phases.build]
cmds = [
  "npm run build",
  "npm prune --production",
  "npm cache clean --force"
]

[start]
cmd = "npm run start"

