# Configuración de Coolify para documentación MCP Financiero
# Este archivo ayuda a Coolify a entender cómo desplegar la aplicación

# Usar Dockerfile para el build
buildPack: dockerfile

# Puerto que expone la aplicación
port: 80

# Ruta del Dockerfile
dockerfilePath: ./Dockerfile

# Health check para verificar que la app está funcionando
healthcheck:
  path: /documentation.html
  interval: 30s
  timeout: 10s
  retries: 3

# Variables de entorno (opcional)
environment:
  TZ: America/Mexico_City

