version: '3.8'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-financiero-docs
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - TZ=America/Mexico_City
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/documentation.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

